### PR TITLE
Jenny: Individual Signup Pages

### PR DESCRIPTION
**Pull request by jennysukut**
This PR covers all the info needed for fellow's profile population! 😃 

There are 5 steps/pages used to handle the profile data and they talk to the fellowContext to update info. 
I've made custom input components and modals to be used in these processes. I've outlined details of all the components in the README file to be referenced + reviewed!
Currently, we're using a fellowContext to hold the data, but we will probably do a mix of that and our database for MVP. 

Since all the 5 pages are so similar, the PR is rather large, but the elements are basically the same. 
{I might be able to do a little video walk-through of how things work if we need to do a review of the PR, or perhaps it's only necessary to look at one or two of the individual signup pages to see if things are written well.}

### CODE REVIEW

**Comment by jennysukut** [comment]
It looks like there are differences in the README, I might just go in and copy Vinay's additions and paste them into my version of the README?

**Comment by lean1190** [comment]
> It looks like there are differences in the README, I might just go in and copy Vinay's additions and paste them into my version of the README?

Yes, you can do that @jennysukut

**Comment by lean1190** [comment]
@jennysukut considering the size of this PR, I suggest you let us know what specific things you would like us to give you feedback about so we can focus on them.

**Comment by jennysukut** [comment]
> @jennysukut considering the size of this PR, I suggest you let us know what specific things you would like us to give you feedback about so we can focus on them.

For sure! Thanks @lean1190  I'm still working at adjusting a few things on this PR, so I'll let you know once I've got a specific page or detail to have you look at. If I get a review of a single page, it should be good to merge 😄 

p.s. I've been messaging on Discord for this, but it might be easier to add notes here directly for things associated with PRs - what do you think?

**Pull request merged**
